const topicNames = { language: "專注力與學習效率", emotion: "情緒壓力與上學", attention: "人際社交與特質", school: "學校適應與拒學" };
const questions = {
  language: ["孩子是否常因容易分心、拖延或難以規劃，而無法完成作業？", "孩子是否常聽完課或讀完題目，仍很難抓到重點？", "這個困擾是否已影響作業完成、考試或課堂參與？", "你是否從老師或孩子口中，聽到類似的學習困難？"],
  emotion: ["焦慮、低落、易怒或強烈抗拒上學的情況，是否每週多次出現？", "這些情況是否影響出缺席、睡眠、食慾、課業或家庭生活？", "孩子是否很難在可信任的大人陪伴下慢慢平復？", "你是否注意到孩子近期明顯比以前更退縮、易怒或失去興趣？"],
  attention: ["孩子在同儕互動中，是否常感到孤立、衝突或難以理解對方的意思？", "孩子是否對改變、特定聲音、觸感或環境特別不舒服？", "孩子是否常有固定的做法或強烈興趣，改變時容易焦慮或衝突？", "這些情況是否已影響學習、自信、人際或日常生活？"],
  school: ["孩子是否常因肚子痛、頭痛、睡不好或其他不舒服，而抗拒、遲到或缺席上學？", "孩子是否常因課業、同儕或師生互動而在上學前後特別焦慮、生氣或沉默？", "這個情況是否已影響出缺席、課業、人際或家庭生活？", "你是否已和孩子、導師或輔導老師討論過，但困擾仍持續或變得更明顯？"]
};
const topicGrid = document.querySelector('#topicGrid'), panel = document.querySelector('#guidePanel'), ageOptions = document.querySelector('#ageOptions');
const guideIntro = document.querySelector('#guideIntro'), questionnaire = document.querySelector('#questionnaire'), result = document.querySelector('#result');
let selectedTopic, selectedAge;

topicGrid.addEventListener('click', e => { const card = e.target.closest('[data-topic]'); if (!card) return; selectedTopic = card.dataset.topic; document.querySelectorAll('.topic-card').forEach(x => x.classList.toggle('selected', x === card)); panel.hidden = false; guideIntro.hidden = false; questionnaire.hidden = true; result.hidden = true; document.querySelector('#selectedTopicLabel').textContent = topicNames[selectedTopic]; document.querySelector('#topicSafety').hidden = !['emotion','school'].includes(selectedTopic); panel.scrollIntoView({behavior:'smooth',block:'nearest'}); });
ageOptions.addEventListener('click', e => { const button = e.target.closest('button'); if (!button) return; selectedAge = button.dataset.age; showQuestions(); });
function showQuestions(){ guideIntro.hidden=true; questionnaire.hidden=false; document.querySelector('.stepper').innerHTML='<span>1 選擇階段</span><i></i><span class="active">2 整理觀察</span><i></i><span>3 下一步</span>'; document.querySelector('#questionMeta').textContent=`${selectedAge} ・ ${topicNames[selectedTopic]}`; document.querySelector('#questionTitle').textContent='請勾選較接近孩子現在的狀況'; document.querySelector('#questions').innerHTML=questions[selectedTopic].map((q,i)=>`<fieldset class="question"><legend>${i+1}. ${q}</legend><div class="answers"><label><input required type="radio" name="q${i}" value="0"> 不太像</label><label><input required type="radio" name="q${i}" value="1"> 偶爾如此</label><label><input required type="radio" name="q${i}" value="2"> 常常如此</label></div></fieldset>`).join(''); }
document.querySelector('#backToAges').addEventListener('click',()=>{guideIntro.hidden=false;questionnaire.hidden=true;document.querySelector('.stepper').innerHTML='<span class="active">1 選擇階段</span><i></i><span>2 整理觀察</span><i></i><span>3 下一步</span>';});
questionnaire.addEventListener('submit', e=>{e.preventDefault();const score=[...new FormData(questionnaire).values()].reduce((n,x)=>n+Number(x),0);showResult(score);});
function showResult(score){ questionnaire.hidden=true; result.hidden=false; document.querySelector('.stepper').innerHTML='<span>1 選擇階段</span><i></i><span>2 整理觀察</span><i></i><span class="active">3 下一步</span>'; let level = score >= 6 ? 'soon' : score >= 3 ? 'talk' : 'watch'; const data={watch:{badge:'持續陪伴觀察',title:'先把日常情況看得更清楚',summary:'目前可先持續留意孩子在不同情境下的表現；若困擾持續、加劇或影響學習與生活，隨時帶著紀錄找人討論。',steps:['選一個最常發生的情境，連續記錄兩週。','找一個孩子較能放鬆的時刻，先聽聽他怎麼看這件事。','若你仍感到不安，主動和導師或輔導老師聊聊。'],who:'可以先找熟悉孩子的導師、輔導老師或其他照顧者交流，看看在不同情境是否有相似觀察。'},talk:{badge:'建議近期討論',title:'這份觀察，值得找人一起看看',summary:'這些困擾已可能影響孩子的學習、生活或人際。先蒐集家中與學校的具體例子，會讓後續討論更有方向。',steps:['用「國中學習與情緒觀察表」記下至少三次具體事件。','邀請導師或輔導老師描述孩子在課堂與同儕互動中的表現及有效做法。','帶著紀錄和學校輔導人員、醫療或心理專業諮詢。'],who:'可先和導師、輔導老師或特教業務承辦人討論；依主要困擾，也可諮詢身心科、心理師、職能治療師或其他相關專業。'},soon:{badge:'建議儘快評估',title:'請盡快讓專業人員陪你一起了解',summary:'困擾看起來已較明顯或持續影響學習、生活、人際與上學。及早找專業支持不是替孩子貼標籤，而是為了找到合適的協助。',steps:['整理出缺席、作業、考試與學校觀察等資料。','記錄具體情境；若合適，也可保留短影片或孩子願意分享的內容供專業人員參考。','近期和學校輔導室討論，並安排醫療或心理相關專業諮詢。'],who:'建議近期諮詢學校輔導室與醫療／心理專業，並和導師、特教業務承辦人同步討論可提供的校內支持。'}}[level];document.querySelector('#resultBadge').textContent=data.badge;document.querySelector('#resultTitle').textContent=data.title;document.querySelector('#resultSummary').textContent=data.summary;document.querySelector('#nextSteps').innerHTML=data.steps.map(x=>`<li>${x}</li>`).join('');document.querySelector('#whoToTalk').textContent=data.who;renderRecommendedTools(score);result.focus();}
document.querySelector('#restart').addEventListener('click',()=>{panel.hidden=true;document.querySelectorAll('.topic-card').forEach(x=>x.classList.remove('selected'));panel.scrollIntoView({behavior:'smooth'});});
const modal = document.querySelector('#toolDialog'); const tools={diary:{title:'國中學習與情緒觀察表',intro:'每次只要記下一個事件即可，不必追求完整。',body:'<h3>事件紀錄</h3><div class="blank-lines"><div>日期／時間：</div><div>當時的情境：課堂、作業、同儕互動、上學前後或家庭中？</div><div>我看到孩子做了什麼、說了什麼？</div><div>大人或學校如何回應？後來發生什麼？</div><div>我想進一步了解的事：</div></div>'},teacher:{title:'與導師／輔導老師溝通卡',intro:'從共同觀察開始，讓對話更容易展開。',body:'<h3>可以這樣問老師</h3><ul><li>「您能描述兩三個孩子在課堂、作業或同儕互動中卡住的具體例子嗎？」</li><li>「在什麼情況下，孩子比較能投入、完成任務或平穩下來？」</li><li>「學校已經嘗試過哪些方式？哪些對孩子有幫助？」</li><li>「我們是否可以先共同觀察兩週，再約時間交流？」</li></ul>'},consult:{title:'校內支持與諮詢準備清單',intro:'帶著這些資料，能幫助學校或專業人員更快了解孩子。',body:'<ul class="checklist"><li>我最想討論的困擾與持續時間</li><li>2–3 個具體的課業、情緒或人際事件紀錄</li><li>導師、輔導老師或其他照顧者的觀察</li><li>出缺席、作業、考試或既有評估等相關資料</li><li>若合適，可供說明的短影片或孩子願意分享的內容</li><li>我想問學校或專業人員的問題</li></ul>'}};
const toolCatalog={diary:{label:'家長紀錄工具',title:'國中學習與情緒觀察表',description:'記錄課業、情緒、人際或出缺席的具體情況，找出可討論的線索。',type:'print'},teacher:{label:'家長溝通工具',title:'與導師／輔導老師溝通卡',description:'用具體提問，了解孩子在課堂、下課與團體中的實際表現。',type:'print'},consult:{label:'家長準備工具',title:'校內支持與諮詢準備清單',description:'先整理資料與問題，讓校內討論或專業諮詢更有收穫。',type:'print'},snap:{label:'醫療機構公開量表',title:'SNAP-IV 注意力與過動量表',description:'當孩子容易分心、坐不住或衝動時，可由家長依近況填寫，作為討論資料。',className:'snap-card',url:'https://www.vghtc.gov.tw/News_Content/2782/14567',action:'前往臺中榮總量表 ↗'},learning:{label:'學校專業評估資源',title:'學習困難質性觀察與鑑定建議',description:'正式的學習障礙檢核與評估應由學校專業人員使用；家長可帶著觀察與老師共同討論。',className:'learning-card',url:'https://teachers.dale.nthu.edu.tw/?page_id=208',action:'查看學習障礙鑑定建議工具 ↗'},sdq:{label:'官方公開問卷',title:'SDQ 雙面版：情緒與適應篩檢',description:'可由學生、家長與教師分別填寫，整理困擾對生活、學習與人際的影響。',className:'sdq-card',url:'https://www.sdqinfo.org/py/sdqinfo/b3.py?language=Chinese',action:'前往 SDQ 官方中文版 ↗'},mood:{label:'官方公開問卷',title:'青少年憂鬱情緒自我檢視',description:'適用 12–18 歲；建議先徵詢孩子是否願意使用，不強迫填寫。',className:'mood-card',url:'https://www.etmh.org/Online_tool/',action:'前往董氏基金會檢視表 ↗'},gad:{label:'政府心理健康資源',title:'GAD-7 焦慮症狀量表',description:'適合以長期擔心、緊繃或難以放鬆為主要困擾時，作為和心理或醫療專業討論的起點。',className:'anxiety-card',url:'https://mental.tycg.gov.tw/News_Content.aspx?n=525&s=333501',action:'查看 GAD-7 政府說明 ↗'},aq:{label:'官方公開問卷',title:'AQ 青少年自閉症量表',description:'適用 12–15 歲，由家長依孩子日常情況填寫；僅整理自閉光譜特質，不作診斷。',className:'aq-card',url:'https://docs.autismresearchcentre.com/tests/AQ_Adolescent_Chinese.pdf',action:'開啟 AQ 繁體中文版 ↗'}};
function openTool(key){const t=tools[key];document.querySelector('#toolContent').innerHTML=`<article class="print-sheet"><p class="eyebrow">家長行動指南</p><h2 id="toolDialogTitle">${t.title}</h2><p>${t.intro}</p>${t.body}<div class="dialog-actions"><button class="button primary" onclick="window.print()">列印這張工具卡</button><button class="button secondary" onclick="document.querySelector('#toolDialog').close()">關閉</button></div></article>`;modal.showModal();}
function renderToolCards(keys){return keys.map((key,index)=>{const t=toolCatalog[key];const button=t.type==='print'?`<button class="button secondary print-tool" data-tool="${key}" type="button">查看／列印</button>`:`<a class="button primary" href="${t.url}" target="_blank" rel="noreferrer">${t.action}</a>`;return `<article class="tool-card ${t.className||''}"><span class="tool-number">${String(index+1).padStart(2,'0')} ・ ${t.label}</span><h3>${t.title}</h3><p>${t.description}</p>${button}</article>`;}).join('');}
function renderRecommendedTools(score){const byTopic={language:['snap','learning'],emotion:['sdq','mood','gad'],attention:['sdq','aq'],school:['sdq','mood']};document.querySelector('#immediateTools').innerHTML=renderToolCards(['diary','teacher','consult']);document.querySelector('#recommendedTools').innerHTML=renderToolCards(byTopic[selectedTopic]);document.querySelector('#resultSafety').hidden=!(['emotion','school'].includes(selectedTopic)&&score>=3);}
document.addEventListener('click',e=>{const button=e.target.closest('.print-tool');if(button)openTool(button.dataset.tool);});
document.querySelector('.dialog-close').addEventListener('click',()=>modal.close());
